DROP TABLE IF EXISTS sessions RESTRICT;

CREATE TABLE sessions(
	session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_id INTEGER NOT NULL,
	scheduled_start TIMESTAMPTZ NOT NULL,
	scheduled_end TIMESTAMPTZ NOT NULL,
	actual_start TIMESTAMPTZ,
	actual_end TIMESTAMPTZ,
	session_type session_type_enum NOT NULL,
	status status_enum NOT NULL DEFAULT 'Upcoming',
	created_on TIMESTAMPTZ NOT NULL DEFAULT NOW(),

	CONSTRAINT fk_events
		FOREIGN KEY (event_id)
		REFERENCES events(event_id)
		ON DELETE CASCADE
);