DROP TABLE IF EXISTS session_teams RESTRICT;

CREATE TABLE session_teams(
	session_team_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	session_id INTEGER NOT NULL,
	team_id INTEGER NOT NULL,
	created_on TIMESTAMPTZ NOT NULL DEFAULT NOW(),

	CONSTRAINT fk_sessions
	FOREIGN KEY (session_id)
	REFERENCES sessions(session_id),

	CONSTRAINT fk_teams
	FOREIGN KEY (team_id)
	REFERENCES teams(team_id),

	CONSTRAINT uq_session_team
	UNIQUE(session_id, team_id)
);