DROP TABLE IF EXISTS team_users RESTRICT;

CREATE TABLE team_users (
	team_user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

	team_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,

	start_date DATE NOT NULL,
	end_date DATE,
	
	created_on TIMESTAMPTZ NOT NULL DEFAULT NOW(),

	CONSTRAINT fk_teams
		FOREIGN KEY (team_id)
		REFERENCES teams(team_id),

	CONSTRAINT fk_users
		FOREIGN KEY (user_id)
		REFERENCES users(user_id)

);
