DROP TABLE IF EXISTS user_roles RESTRICT;

CREATE TABLE user_roles (
	user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id INTEGER NOT NULL,
	role_id INTEGER NOT NULL,

	CONSTRAINT fk_users
	FOREIGN KEY (user_id)
	REFERENCES users(user_id),

	CONSTRAINT fk_roles
	FOREIGN KEY (role_id)
	REFERENCES roles(role_id),

	CONSTRAINT uq_user_role
	UNIQUE (user_id, role_id)

);