DROP TABLE IF EXISTS team_members RESTRICT;

CREATE TABLE team_members (
	team_member_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	team_id INTEGER NOT NULL,
	member_id INTEGER NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE,
	team_position team_position_enum NOT NULL DEFAULT 'Player',
	created_on TIMESTAMPTZ NOT NULL DEFAULT NOW(),

	CONSTRAINT fk_members
	FOREIGN KEY (member_id)
	REFERENCES members(member_id),

	CONSTRAINT fk_teams
	FOREIGN KEY (team_id)
	REFERENCES teams(team_id)
);