DROP TABLE IF EXISTS session_teams;
DROP TABLE IF EXISTS team_members;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS team_users;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

DROP TYPE IF EXISTS session_type_enum;
DROP TYPE IF EXISTS status_enum;
DROP TYPE IF EXISTS team_position_enum;